# Generated by Django 3.1 on 2020-08-17 03:59

import apps.app_base.validators
import apps.account.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tbl_account',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ tên')),
                ('avatar', models.ImageField(blank=True, help_text='File upload có định dạng image và có dung lượng nhỏ hơn 10MB', null=True, upload_to=apps.account.models.upload_avatar_path, validators=[apps.app_base.validators.validate_image_size, apps.app_base.validators.validate_file_extension_image], verbose_name='Ảnh đại diện')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Nữ'), ('male', 'Nam')], max_length=50, null=True, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày tháng năm sinh')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)], verbose_name='Vĩ độ / latitude')),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)], verbose_name='Kinh độ / longitude')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Thông tin mở rộng')),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True, validators=[apps.app_base.validators.validate_email_field], verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
                'db_table': 'tbl_personal',
            },
        ),
        migrations.CreateModel(
            name='BlacklistToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('blacklisted_on', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'verbose_name': 'Blacklist Token',
                'verbose_name_plural': 'Blacklist Token',
                'db_table': 'tbl_blacklist_token',
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='tbl_account_usernam_0ad0f3_idx'),
        ),
    ]
