# Generated by Django 3.1 on 2020-08-26 04:11

import apps.account.models
import apps.app_base.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Họ tên')),
                ('avatar', models.ImageField(blank=True, help_text='File upload có định dạng image và có dung lượng nhỏ hơn 10MB', null=True, upload_to=apps.account.models.upload_avatar_path, validators=[apps.app_base.validators.validate_image_size, apps.app_base.validators.validate_file_extension_image], verbose_name='Ảnh đại diện')),
                ('gender', models.CharField(blank=True, choices=[('female', 'Nữ'), ('male', 'Nam')], max_length=50, null=True, verbose_name='Giới tính')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày tháng năm sinh')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Địa chỉ')),
                ('extra_info', models.TextField(blank=True, null=True, verbose_name='Thông tin mở rộng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Thông tin người dùng',
                'verbose_name_plural': 'Thông tin người dùng',
                'db_table': 'account_user_info',
            },
        ),
        migrations.RemoveField(
            model_name='personal',
            name='account',
        ),
        migrations.RemoveField(
            model_name='blacklisttoken',
            name='account',
        ),
        migrations.AddField(
            model_name='blacklisttoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='blacklisttoken',
            table='account_blacklist_token',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
